# Q1

In [1]:
# 1.
import pandas as pd

data_dict = {
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
}

df_obj = pd.DataFrame(data_dict)
df_obj

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [2]:
# 2.
df_obj.head(1)

  name  score gender
0  Tom     85      男

In [3]:
df_obj.shape

(3, 3)

In [4]:
df_obj.columns

Index(['name', 'score', 'gender'], dtype='object')

In [5]:
df_obj.dtypes

name      object
score      int64
gender    object
dtype: object

In [6]:
# 3.
data_list = [[1,"A"],[2,"B"],[3,"C"]]
df_list = pd.DataFrame(data_list,columns = ['id','tag'])
df_list

   id tag
0   1   A
1   2   B
2   3   C

# Q2

In [7]:
# 1.
df_obj[['score','gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [8]:
# 2.
df_obj.loc[[0,2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [9]:
# 3. 
df_obj[df_obj['score'] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [10]:
# 4.
df_obj['grade'] = "良好"   #新建一列，里面的值均为良好
df_obj.loc[df_obj['score']>=90,'grade']= '优秀'
df_obj

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [11]:
# 5.
df_obj.drop('gender',axis = 1,inplace = True)
df_obj

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

# Q3

In [12]:
# 1.
data = {"x":[1,None,3],"y":[None,5,6]}
df_obj = pd.DataFrame(data)
df_obj

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [13]:
df_obj.isnull()  #检测缺失值
df_obj.isnull().sum() #统计每列缺失数量

x    1
y    1
dtype: int64

In [14]:
# 2.
df_obj.fillna(0)

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [15]:
df_obj.dropna()

     x    y
2  3.0  6.0

# Q4

In [16]:
df_obj = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
})
df_obj

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [17]:
# 1.
df_obj.groupby('gender')['score'].agg(['mean','max'])

        mean  max
gender
女       92.0   92
男       81.5   85

In [18]:
# 2.
df_obj.groupby('gender').size()

gender
女    1
男    2
dtype: int64

# Q5

In [19]:
# 1.
df_obj.sort_values('score',ascending = True)

    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

In [20]:
# 2.
df_obj.loc[3] = ['Tom',85,'男']
df_obj

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男
3    Tom     85      男

In [30]:
?pd.DataFrame.drop_duplicates

Signature:
pd.DataFrame.drop_duplicates(
    self,
    subset: 'Hashable | Sequence[Hashable] | None' = None,
    *,
    keep: 'DropKeep' = 'first',
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Return DataFrame with duplicate rows removed.

Considering certain columns is optional. Indexes, including time indexes
are ignored.

Parameters
----------
subset : column label or sequence of labels, optional
    Only consider certain columns for identifying duplicates, by
    default use all of the columns.
keep : {'first', 'last', ``False``}, default 'first'
    Determines which duplicates (if any) to keep.

    - 'first' : Drop duplicates except for the first occurrence.
    - 'last' : Drop duplicates except for the last occurrence.
    - ``False`` : Drop all duplicates.

inplace : bool, default ``False``
    Whether to modify the DataFrame rather than creating a new one.
ignore_index : bool, default ``False``
    If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

Returns
-------
DataFrame or None
    DataFrame with duplicates removed or None if ``inplace=True``.

See Also
--------
DataFrame.value_counts: Count unique combinations of columns.

Examples
--------
Consider dataset containing ramen rating.

>>> df = pd.DataFrame({
...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
...     'rating': [4, 4, 3.5, 15, 5]
... })
>>> df
    brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

By default, it removes duplicate rows based on all columns.

>>> df.drop_duplicates()
    brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

To remove duplicates on specific column(s), use ``subset``.

>>> df.drop_duplicates(subset=['brand'])
    brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5

To remove duplicates and keep last occurrences, use ``keep``.

>>> df.drop_duplicates(subset=['brand', 'style'], keep='last')
    brand style  rating
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
4  Indomie  pack     5.0
File:      c:\users\jiangjiang\miniconda3\envs\jdl\lib\site-packages\pandas\core\frame.py
Type:      function

In [32]:
# 去重
df_obj.drop_duplicates(keep = 'first')

    name  score gender  score_std
0    Tom     85      男   0.000000
1  Jerry     92      女   1.224745
2   Mike     78      男  -1.224745

# Q6

In [22]:
# 1.
df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})
df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})
pd.merge(df1,df2,on = 'id')

   id name  age
0   1    X   20
1   2    Y   30

In [23]:
# 2.
df_a = pd.DataFrame ({"val":[1,2]})
df_b = pd.DataFrame ({"val":[3,4]})
pd.concat([df_a,df_b],ignore_index = True)

   val
0    1
1    2
2    3
3    4

# Q7

In [24]:
# 1.
date_list = ["2025-01-01","2025-01-02","2025-01-03"]
date_a = pd.to_datetime(date_list)
date_a

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03'], dtype='datetime64[ns]', freq=None)

In [25]:
# 2.
date_a.month #月份

Index([1, 1, 1], dtype='int32')

In [26]:
date_a.day_name()  #星期

Index(['Wednesday', 'Thursday', 'Friday'], dtype='object')

# Q8

In [27]:
# 1.
df_obj['score_std'] = (df_obj['score']- df_obj['score'].mean()) / df_obj['score'].std()
df_obj

    name  score gender  score_std
0    Tom     85      男   0.000000
1  Jerry     92      女   1.224745
2   Mike     78      男  -1.224745
3    Tom     85      男   0.000000

In [28]:
# 2.
pd.pivot_table(df_obj,index = 'gender',values = 'score',aggfunc = 'median')

        score
gender
女        92.0
男        85.0